version: '3'

services:
  init-postgresql:
    container_name: init-postgresql
    environment:
      LC_CTYPE: en_US.utf8
#     See https://github.com/Senzing/init-postgresql#configuration
      SENZING_CONFIGURATION_MODIFICATIONS: |
        addDataSource CUSTOMERS
        addDataSource REFERENCE
        addDataSource WATCHLIST
      SENZING_ENGINE_CONFIGURATION_JSON: ${SENZING_ENGINE_CONFIGURATION_JSON}
      SENZING_SUBCOMMAND: mandatory
    image: senzing/init-postgresql
    networks:
      - backend
    read_only: true
    restart: on-failure

networks:
  backend:
